OC.L10N.register(
    "impersonate",
    {
    "Could not impersonate user" : "Níorbh fhéidir aithris a dhéanamh ar an úsáideoir",
    "Are you sure you want to impersonate \"{userId}\"?" : "An bhfuil tú cinnte gur mhaith leat \"{userId}\" a phearsanú?",
    "Impersonate user" : "Déan aithris ar an úsáideoir",
    "Impersonate" : "Déan aithris",
    "Could not log out, please try again" : "Níorbh fhéidir logáil amach, bain triail eile as le do thoil",
    "Logged in as {name} ({uid})" : "Logáilte isteach mar {name} ({uid})",
    "User not found" : "Úsáideoir gan aimsiú",
    "Insufficient permissions to impersonate user" : "Níl go leor ceadanna chun aithris a dhéanamh ar an úsáideoir",
    "Cannot impersonate the user because it was never logged in" : "Ní féidir aithris a dhéanamh ar an úsáideoir toisc nach raibh sé logáilte isteach riamh",
    "Cannot impersonate yourself" : "Ní féidir aithris a dhéanamh ort féin",
    "Impersonate other users" : "Déan aithris ar úsáideoirí eile",
    "By installing the impersonate app of your Nextcloud you enable administrators to impersonate other users on the Nextcloud server. This is especially useful for debugging issues reported by users.\n\nTo impersonate a user an administrator has to simply follow the following four steps:\n\n1. Login as administrator to Nextcloud.\n2. Open users administration interface.\n3. Select the impersonate button on the affected user.\n4. Confirm the impersonation.\n\nThe administrator is then logged-in as the user, to switch back to the regular user account they simply have to press the logout button.\n\n**Note:**\n\n- This app is not compatible with instances that have encryption enabled.\n- While impersonate actions are logged note that actions performed impersonated will be logged as the impersonated user.\n- Impersonating a user is only possible after their first login.\n- You can limit which users/groups can use impersonation in Administration settings > Additional settings." : "Trí aip phearsanta do Nextcloud a shuiteáil cuireann tú ar chumas riarthóirí daoine eile a phearsanú ar fhreastalaí Nextcloud. Tá sé seo úsáideach go háirithe le haghaidh saincheisteanna dífhabhtaithe a thuairiscíonn úsáideoirí.\n\nChun aithris a dhéanamh ar úsáideoir ní mór do riarthóir na ceithre chéim seo a leanas a leanúint:\n\n1. Logáil isteach mar riarthóir ar Nextcloud.\n2. Oscail comhéadan riaracháin úsáideoirí.\n3. Roghnaigh an cnaipe aithris a dhéanamh ar an úsáideoir lena mbaineann.\n4. Deimhnigh an pearsanú.\n\nTá an riarthóir logáilte isteach mar úsáideoir ansin, chun aistriú ar ais go dtí an gnáthchuntas úsáideora níl le déanamh acu ach an cnaipe logála amach a bhrú.\n\n**Nóta:**\n\n- Níl an app seo ag luí le cásanna a bhfuil criptiú cumasaithe acu.\n- Cé go ndéantar gníomhartha pearsanaithe a logáil tabhair faoi deara go ndéanfar gníomhartha a dhéantar a phearsanú a logáil mar úsáideoir pearsanaithe.\n- Ní féidir aithris a dhéanamh ar úsáideoir ach amháin tar éis a gcéad logáil isteach.\n- Is féidir leat teorainn a chur leis na húsáideoirí/grúpaí ar féidir leo pearsanú a úsáid i socruithe Riaracháin > Socruithe breise.",
    "These groups will be able to impersonate users they are allowed to administrate. If you remove all groups, every group administrator will be allowed to impersonate." : "Beidh na grúpaí seo in ann aithris a dhéanamh ar na húsáideoirí a bhfuil cead acu a riar. Má bhaineann tú gach grúpa, beidh cead ag gach riarthóir grúpa pearsanú a dhéanamh.",
    "By installing the impersonate app of your Nextcloud you enable administrators to impersonate other users on the Nextcloud server. This is especially useful for debugging issues reported by users.\n\nTo impersonate a user an administrator has to simply follow the following four steps:\n\n1. Login as administrator to Nextcloud.\n2. Open users administration interface.\n3. Select the impersonate button on the affected user.\n4. Confirm the impersonation.\n\nThe administrator is then logged-in as the user, to switch back to the regular user account they simply have to press the logout button.\n\n**Note:**\n\n- This app is not compatible with instances that have encryption enabled.\n- While impersonate actions are logged note that actions performed impersonated will be logged as the impersonated user.\n- Impersonating a user is only possible after their first login." : "Trí aip phearsanta do Nextcloud a shuiteáil cuireann tú ar chumas riarthóirí daoine eile a phearsanú ar fhreastalaí Nextcloud. Tá sé seo úsáideach go háirithe le haghaidh saincheisteanna dífhabhtaithe a thuairiscíonn úsáideoirí.\n\nChun aithris a dhéanamh ar úsáideoir ní mór do riarthóir na ceithre chéim seo a leanas a leanúint:\n\n1. Logáil isteach mar riarthóir ar Nextcloud.\n2. Oscail comhéadan riaracháin úsáideoirí.\n3. Roghnaigh an cnaipe aithris a dhéanamh ar an úsáideoir lena mbaineann.\n4. Deimhnigh an pearsanú.\n\nTá an riarthóir logáilte isteach mar úsáideoir ansin, chun aistriú ar ais go dtí an gnáthchuntas úsáideora níl le déanamh acu ach an cnaipe logála amach a bhrú.\n\n**Nóta:**\n\n- Níl an app seo ag luí le cásanna a bhfuil criptiú cumasaithe acu.\n- Cé go ndéantar gníomhartha pearsanaithe a logáil tabhair faoi deara go ndéanfar gníomhartha a dhéantar a phearsanú a logáil mar úsáideoir pearsanaithe.\n- Ní féidir aithris a dhéanamh ar úsáideoir ach amháin tar éis a gcéad logáil isteach."
},
"nplurals=5; plural=(n==1 ? 0 : n==2 ? 1 : n<7 ? 2 : n<11 ? 3 : 4);");
