OC.L10N.register(
    "impersonate",
    {
    "Could not impersonate user" : "Kon gebruiker niet imiteren",
    "Are you sure you want to impersonate \"{userId}\"?" : "Weet je zeker dat je \"{userId}\" wilt imiteren?",
    "Impersonate user" : "Gebruiker imiteren",
    "Impersonate" : "Imiteren",
    "Logged in as {uid}" : "Ingelogd in {uid}",
    "User not found" : "Gebruiker niet gevonden",
    "Insufficient permissions to impersonate user" : "Onvoldoende rechten om andere account te imiteren.",
    "Can not impersonate the user because it was never logged in." : "Kan deze gebruiker niet impersoneren omdat deze nooit ingelogd is geweest.",
    "Impersonate other users" : "Andere gebruiker imiteren",
    "By installing the impersonate app of your Nextcloud you enable administrators to impersonate other users on the Nextcloud server. This is especially useful for debugging issues reported by users.\n\nTo impersonate a user an administrator has to simply follow the following four steps:\n\n1. Login as administrator to Nextcloud\n2. Open the user administration interface\n3. Select the impersonate button on the affected user\n4. Confirm the impersonation\n\nThe administrator is then logged-in as the user, to switch back to the regular user account they simply have to press the logout button.\n\n**Note:**\n\n- This app is not compatible with instances that have encryption enabled.\n- While impersonate actions are logged note that actions performed impersonated will be logged as the impersonated user.\n- Impersonating an user is only possible after their first login." : "Door installeren van de Imiteer app van je Nextcloud kunnen beheerders andere gebruikers op Nextcloud imiteren. Dit kan van belang zijn voor oplossen van problemen die door gebruikers zijn gemeld.\n\nEn een gebruiker te imiteren, moet een beheerder de volgende stappen uitvoeren:\n\n1. Als beheerder inloggen in Nextcloud\n2. De gebruikersbeheer interface openen\n3. De Imiteer=knop bij de betreffende gebruiker indrukken\n4. Het imiteren bevestigen\n\nDe beheerder is dan ingelogd als de gebruiker. Om terug te schakelen naar de reguliere gebruikersaccount, is indrukken van de uitlog-knop voldoende. \n\n**Let op:**\n\n- Deze app is niet compatible met servers waarop versleuteling is ingeschakeld..\n- Hoewel Imiteer-acties worden gelogd, worden transacties die onder imitatie worden uitgevoerd, geregistreerd onder de geïmiteerde gebruiker.\n- Imiteren van een gebruiker kan alleen na de eerste inlog van die gebruiker.",
    "These groups will be able to impersonate users they are allowed to administrate. If you remove all groups, every group administrator will be allowed to impersonate." : "Deze groepen kunnen andere gebruikers nadoen als ze bevoegd zijn om te beheren. Als je alle groepen verwijderd, kan iedere groep administrator gebruikers nadoen.",
    "Not enough permissions to impersonate user" : "Onvoldoende rechten om gebruiker te impersoneren.",
    "By installing the impersonate app of your Nextcloud you enable administrators to impersonate other users on the Nextcloud server. This is especially useful for debugging issues reported by users.\n\nTo impersonate an user an administrator has to simply follow the following three steps:\n\n1. Login as administrator to Nextcloud\n2. Open the user administration interface\n3. Select the impersonate button on the affected user\n4. Confirm the impersonation\n\nThe administrator is then logged-in as the user, to switch back to the regular user account they simply have to press the logout button.\n\n**Note:**\n\n- This app is not compatible with instances that have encryption enabled.\n- While impersonate actions are logged note that actions performed impersonated will be logged as the impersonated user.\n- Impersonating an user is only possible after their first login." : "Door installeren van de Imiteer app van je Nextcloud kunnen beheerders andere gebruikers op Nextcloud imiteren. Dit kan van belang zijn voor oplossen van problemen die door gebruikers zijn gemeld.\n\nEn een gebruiker te imiteren, moet een beheerder de volgende stappen uitvoeren:\n\n1. Als beheerder inloggen in Nextcloud\n2. De gebruikersbeheer interface openen\n3. De Imiteer=knop bij de betreffende gebruiker indrukken\n4. Het imiteren bevestigen\n\nDe beheerder is dan ingelogd als de gebruiker. Om terug te schakelen naar de reguliere gebruikersaccount, is indrukken van de uitlog-knop voldoende. \n\n**Let op:**\n\n- Deze app is niet compatible met servers waarop versleuteling is ingeschakeld..\n- Hoewel Imiteer-acties worden gelogd, worden transacties die onder imitatie worden uitgevoerd, geregistreerd onder de geïmiteerde gebruiker.\n- Imiteren van een gebruiker kan alleen na de eerste inlog van die gebruiker."
},
"nplurals=2; plural=(n != 1);");
