OC.L10N.register(
    "impersonate",
    {
    "Could not impersonate user" : "Nie można podszyć się pod użytkownika",
    "Are you sure you want to impersonate \"{userId}\"?" : "Czy na pewno chcesz podszyć się pod użytkownika \"{userId}\"?",
    "Impersonate user" : "Podszywanie się pod użytkownika",
    "Impersonate" : "Podszywanie",
    "Could not log out, please try again" : "Nie udało się wylogować, spróbuj ponownie",
    "Logged in as {name} ({uid})" : "Zalogowany jako {name} ({uid})",
    "User not found" : "Nie znaleziono użytkownika",
    "Insufficient permissions to impersonate user" : "Niewystarczające uprawnienia do podszycia się pod użytkownika",
    "Cannot impersonate the user because it was never logged in" : "Nie można podszyć się pod użytkownika, ponieważ nigdy nie był zalogowany",
    "Cannot impersonate yourself" : "Nie możesz podszyć się pod siebie samego",
    "Impersonate other users" : "Podszyj się pod innych użytkowników",
    "By installing the impersonate app of your Nextcloud you enable administrators to impersonate other users on the Nextcloud server. This is especially useful for debugging issues reported by users.\n\nTo impersonate a user an administrator has to simply follow the following four steps:\n\n1. Login as administrator to Nextcloud.\n2. Open users administration interface.\n3. Select the impersonate button on the affected user.\n4. Confirm the impersonation.\n\nThe administrator is then logged-in as the user, to switch back to the regular user account they simply have to press the logout button.\n\n**Note:**\n\n- This app is not compatible with instances that have encryption enabled.\n- While impersonate actions are logged note that actions performed impersonated will be logged as the impersonated user.\n- Impersonating a user is only possible after their first login.\n- You can limit which users/groups can use impersonation in Administration settings > Additional settings." : "Instalując aplikację \"Impersonate\" w swoim Nextcloud, umożliwiasz administratorom podszywanie się pod innych użytkowników na serwerze Nextcloud. Jest to szczególnie przydatne do debugowania problemów zgłaszanych przez użytkowników.\n\nAby podszyć się pod użytkownika, administrator musi wykonać cztery kroki:\n\n1. Zalogować się jako administrator do Nextcloud.\n2. Otworzyć interfejs administracyjny użytkowników.\n3. Wybrać przycisk \"Podszywanie\" przy danym użytkowniku.\n4. Potwierdzić podszycie.\n\nAdministrator jest następnie zalogowany jako dany użytkownik. Aby wrócić do zwykłego konta administratora, wystarczy nacisnąć przycisk wylogowania.\n\n**Uwaga:**\n\n- Ta aplikacja nie jest kompatybilna z instancjami, które mają włączone szyfrowanie.\n- Chociaż akcje podszywania się są logowane, to działania wykonywane podczas podszywania będą logowane jako wykonywane przez użytkownika, pod którego się podszyto.\n- Podszywanie się pod użytkownika jest możliwe dopiero po jego pierwszym logowaniu.\n- Możesz ograniczyć, którzy użytkownicy/grupy mogą korzystać z tej funkcji w ustawieniach administracyjnych > Ustawienia dodatkowe.",
    "These groups will be able to impersonate users they are allowed to administrate. If you remove all groups, every group administrator will be allowed to impersonate." : "Grupy te będą mogły podszywać się za użytkowników, dla których mają uprawnienia do administrowania. Jeśli usuniesz wszystkie grupy, każdy administrator grupy będzie mógł podszyć się pod nich."
},
"nplurals=4; plural=(n==1 ? 0 : (n%10>=2 && n%10<=4) && (n%100<12 || n%100>14) ? 1 : n!=1 && (n%10>=0 && n%10<=1) || (n%10>=5 && n%10<=9) || (n%100>=12 && n%100<=14) ? 2 : 3);");
