OC.L10N.register(
    "impersonate",
    {
    "Could not impersonate user" : "Não foi possível fazer-se passar por outro utilizador",
    "Are you sure you want to impersonate \"{userId}\"?" : "Tem a certeza que quer fazer-se passar por \"{userId}\"?",
    "Impersonate user" : "Fazer-se passar por outro utilizador",
    "Impersonate" : "Fazer-se passar por",
    "Logged in as {uid}" : "Iniciou sessão como {uid}",
    "User not found" : "Utilizador não encontrado",
    "Insufficient permissions to impersonate user" : "Não tem permissões suficientes para se fazer passar por outro utilizador",
    "Impersonate other users" : "Fazer-se passar por outros utilizadores",
    "By installing the impersonate app of your Nextcloud you enable administrators to impersonate other users on the Nextcloud server. This is especially useful for debugging issues reported by users.\n\nTo impersonate a user an administrator has to simply follow the following four steps:\n\n1. Login as administrator to Nextcloud\n2. Open the user administration interface\n3. Select the impersonate button on the affected user\n4. Confirm the impersonation\n\nThe administrator is then logged-in as the user, to switch back to the regular user account they simply have to press the logout button.\n\n**Note:**\n\n- This app is not compatible with instances that have encryption enabled.\n- While impersonate actions are logged note that actions performed impersonated will be logged as the impersonated user.\n- Impersonating an user is only possible after their first login." : "Ao instalar a aplicação para se fazer passar por outro utilizador do Nextcloud irá permitir que os administradores se façam passar por outros utilizadores no servidor Nextcloud. É particularmente útil para resolver problemas reportados pelos utilizadores.\n\nPara se fazer passar por um utilizador um administrador tem que simplesmente seguir quatro passos:\n\n1. Iniciar sessão como administrador no Nextcloud\n2. Abrir a interface de administração de utilizadores\n3. Usar a opção para se fazer passar pelo utilizador, no menu do utilizador em questão\n4. Confirmar a operação\n\nO administrador irá iniciar a sessão como se fosse esse utilizador. Para voltar à conta original de administrador basta encerrar a sessão.\n\n**Notas:**\n\n- Esta aplicação não é compatível com instâncias que tenham encriptação activada.\n- Embora as operações executadas neste modo sejam registadas, note que são registadas em nome do utilizador pelo qual se está a fazer passar.\n- Fazer-se passar por um utilizador só é possível se esse utilizador já tiver iniciado uma sessão ao menos uma vez.",
    "These groups will be able to impersonate users they are allowed to administrate. If you remove all groups, every group administrator will be allowed to impersonate." : "Os membros destes grupos poderão fazer-se passar pelos utilizadores que tenham permissões para administrar. Se remover todos os grupos, todos os administradores de grupos terão permissão de se fazer passar pelos seus utilizadores."
},
"nplurals=2; plural=(n != 1);");
